print('+---------------------------------------------------------------------+')
print('|                                                          Enero 2023 |')
print('|                                                       Guatemala, GT |')
print('|  Very Good,                                                         |')
print('|                                                                     |')
print('|      Learn the basics of python.                                    |')
print('|      everything is achieved with discipline.                        |')
print('|                                                                     |')
print('|                                                                     |')
print('|                                                                     |')
print('|                                                                     |')
print('|                                              gcboot  🤖             |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')